// auto generated by c2z
#include "errordesc.h"

extern "C" const void* _1_ErrorDescriptor__debug_level_ = (void*)& ::ErrorDescriptor::_debug_level;
extern "C" const void* _1_ErrorDescriptor__out_ = (void*)& ::ErrorDescriptor::_out;
extern "C" ::ErrorDescriptor _1_ErrorDescriptor_init_(Severity s, DebugLevel d) { return ::ErrorDescriptor(s, d); }
extern "C" void _1_ErrorDescriptor_deinit_(::ErrorDescriptor *self) { self->~ErrorDescriptor(); }
extern "C" void _1_ErrorDescriptor_PrintContents_(const ::ErrorDescriptor *self, ostream & out) { self->PrintContents(out); }
extern "C" std::string _1_ErrorDescriptor_severityString_(const ::ErrorDescriptor *self) { return self->severityString(); }
extern "C" Severity _1_ErrorDescriptor_GetCorrSeverity_(::ErrorDescriptor* self, const char * s) { return self->GetCorrSeverity(s); }
extern "C" void _2_ErrorDescriptor_UserMsg_(::ErrorDescriptor* self, const char * msg) { self->UserMsg(msg); }
extern "C" void _1_ErrorDescriptor_AppendToUserMsg_(::ErrorDescriptor* self, const char * msg) { self->AppendToUserMsg(msg); }
extern "C" void _2_ErrorDescriptor_AppendToUserMsg_(::ErrorDescriptor* self, const char c) { self->AppendToUserMsg(c); }
extern "C" void _1_ErrorDescriptor_PrependToUserMsg_(::ErrorDescriptor* self, const char * msg) { self->PrependToUserMsg(msg); }
extern "C" void _3_ErrorDescriptor_DetailMsg_(::ErrorDescriptor* self, const char * msg) { self->DetailMsg(msg); }
extern "C" void _1_ErrorDescriptor_AppendToDetailMsg_(::ErrorDescriptor* self, const char * msg) { self->AppendToDetailMsg(msg); }
extern "C" void _1_ErrorDescriptor_PrependToDetailMsg_(::ErrorDescriptor* self, const char * msg) { self->PrependToDetailMsg(msg); }
extern "C" void _3_ErrorDescriptor_AppendToDetailMsg_(::ErrorDescriptor* self, const char c) { self->AppendToDetailMsg(c); }
