// auto generated by c2z
#include "Registry.h"

extern "C" const void* _1_t_sdaiINTEGER_ = (void*)& ::t_sdaiINTEGER;
extern "C" const void* _1_t_sdaiREAL_ = (void*)& ::t_sdaiREAL;
extern "C" const void* _1_t_sdaiNUMBER_ = (void*)& ::t_sdaiNUMBER;
extern "C" const void* _1_t_sdaiSTRING_ = (void*)& ::t_sdaiSTRING;
extern "C" const void* _1_t_sdaiBINARY_ = (void*)& ::t_sdaiBINARY;
extern "C" const void* _1_t_sdaiBOOLEAN_ = (void*)& ::t_sdaiBOOLEAN;
extern "C" const void* _1_t_sdaiLOGICAL_ = (void*)& ::t_sdaiLOGICAL;
extern "C" void _1_Registry_AddClones_(::Registry* self, const EntityDescriptor & __arg0) { self->AddClones(__arg0); }
extern "C" void _1_Registry_RemoveClones_(::Registry* self, const EntityDescriptor & __arg0) { self->RemoveClones(__arg0); }
extern "C" ::Registry _1_Registry_init_(CF_init initFunct) { return ::Registry(initFunct); }
extern "C" void _1_Registry_deinit_(::Registry *self) { self->~Registry(); }
extern "C" void _1_Registry_DeleteContents_(::Registry* self) { self->DeleteContents(); }
extern "C" const EntityDescriptor * _1_Registry_FindEntity_(const ::Registry *self, const char * __arg0, const char * __arg1, int check_case) { return self->FindEntity(__arg0, __arg1, check_case); }
extern "C" const Schema * _1_Registry_FindSchema_(const ::Registry *self, const char * __arg0, int check_case) { return self->FindSchema(__arg0, check_case); }
extern "C" const TypeDescriptor * _1_Registry_FindType_(const ::Registry *self, const char * __arg0, int check_case) { return self->FindType(__arg0, check_case); }
extern "C" void _1_Registry_AddEntity_(::Registry* self, const EntityDescriptor & __arg0) { self->AddEntity(__arg0); }
extern "C" void _1_Registry_AddSchema_(::Registry* self, const Schema & __arg0) { self->AddSchema(__arg0); }
extern "C" void _1_Registry_AddType_(::Registry* self, const TypeDescriptor & __arg0) { self->AddType(__arg0); }
extern "C" void _1_Registry_RemoveEntity_(::Registry* self, const char * __arg0) { self->RemoveEntity(__arg0); }
extern "C" void _1_Registry_RemoveSchema_(::Registry* self, const char * __arg0) { self->RemoveSchema(__arg0); }
extern "C" void _1_Registry_RemoveType_(::Registry* self, const char * __arg0) { self->RemoveType(__arg0); }
extern "C" int _1_Registry_GetEntityCnt_(::Registry* self) { return self->GetEntityCnt(); }
extern "C" void _1_Registry_ResetEntities_(::Registry* self) { self->ResetEntities(); }
extern "C" const EntityDescriptor * _1_Registry_NextEntity_(::Registry* self) { return self->NextEntity(); }
extern "C" void _1_Registry_ResetSchemas_(::Registry* self) { self->ResetSchemas(); }
extern "C" const Schema * _1_Registry_NextSchema_(::Registry* self) { return self->NextSchema(); }
extern "C" void _1_Registry_ResetTypes_(::Registry* self) { self->ResetTypes(); }
extern "C" const TypeDescriptor * _1_Registry_NextType_(::Registry* self) { return self->NextType(); }
extern "C" SDAI_Application_instance * _1_Registry_ObjCreate_(const ::Registry *self, const char * nm, const char * __arg1, int check_case) { return self->ObjCreate(nm, __arg1, check_case); }
