// auto generated by c2z
#include "sdai.h"

extern "C" const void* _1_SCLversion_ = (void*)& ::SCLversion;
extern "C" const void* _1_SDAI_INT_NULL_ = (void*)& ::SDAI_INT_NULL;
extern "C" const void* _1_SDAI_REAL_NULL_ = (void*)& ::SDAI_REAL_NULL;
extern "C" const void* _1_SDAI_NUMBER_NULL_ = (void*)& ::SDAI_NUMBER_NULL;
extern "C" const void* _1_NilSTEPentity_ = (void*)& ::NilSTEPentity;
extern "C" SDAI_Application_instance * _1_ReadEntityRef_(istream & in, ErrorDescriptor * err, const char * tokenList, InstMgrBase * instances, int addFileId) { return ::ReadEntityRef(in, err, tokenList, instances, addFileId); }
extern "C" SDAI_BOOLEAN * _1_create_BOOLEAN_() { return ::create_BOOLEAN(); }
