// auto generated by c2z
#include "STEPattribute.h"

extern "C" int _1_SetErrOnNull_(const char * attrValue, ErrorDescriptor * error) { return ::SetErrOnNull(attrValue, error); }
extern "C" SDAI_Application_instance * _1_ReadEntityRef_(istream & in, ErrorDescriptor * err, const char * tokenList, InstMgrBase * instances, int addFileId) { return ::ReadEntityRef(in, err, tokenList, instances, addFileId); }
extern "C" SDAI_Application_instance * _2_ReadEntityRef_(const char * s, ErrorDescriptor * err, const char * tokenList, InstMgrBase * instances, int addFileId) { return ::ReadEntityRef(s, err, tokenList, instances, addFileId); }
extern "C" Severity _1_EntityValidLevel_(SDAI_Application_instance * se, const TypeDescriptor * ed, ErrorDescriptor * err) { return ::EntityValidLevel(se, ed, err); }
extern "C" Severity _2_EntityValidLevel_(const char * attrValue, const TypeDescriptor * ed, ErrorDescriptor * err, InstMgrBase * im, int clearError) { return ::EntityValidLevel(attrValue, ed, err, im, clearError); }
extern "C" SDAI_Application_instance * _1_STEPread_reference_(const char * s, ErrorDescriptor * err, InstMgrBase * instances, int addFileId) { return ::STEPread_reference(s, err, instances, addFileId); }
extern "C" int _1_QuoteInString_(istream & in) { return ::QuoteInString(in); }
extern "C" void _1_AppendChar_(char c, int & index, char *& s, int & sSize) { ::AppendChar(c, index, s, sSize); }
extern "C" void _1_PushPastString_(istream & in, std::string & s, ErrorDescriptor * err) { ::PushPastString(in, s, err); }
extern "C" void _1_PushPastImbedAggr_(istream & in, std::string & s, ErrorDescriptor * err) { ::PushPastImbedAggr(in, s, err); }
extern "C" void _1_PushPastAggr1Dim_(istream & in, std::string & s, ErrorDescriptor * err) { ::PushPastAggr1Dim(in, s, err); }
extern "C" ostream & _1_STEPattribute_shiftLeft_(ostream & __arg0, STEPattribute & __arg1) { return __arg0 << __arg1; }
extern "C" char _1_STEPattribute_SkipBadAttr_(::STEPattribute* self, istream & in, char * StopChars) { return self->SkipBadAttr(in, StopChars); }
extern "C" void _1_STEPattribute_AddErrorInfo_(::STEPattribute* self) { self->AddErrorInfo(); }
extern "C" void _1_STEPattribute_STEPwriteError_(::STEPattribute* self, ostream & out, unsigned int line, const char * desc) { self->STEPwriteError(out, line, desc); }
extern "C" Severity _1_STEPattribute_StrToVal_(::STEPattribute* self, const char * s, InstMgrBase * instances, int addFileId) { return self->StrToVal(s, instances, addFileId); }
extern "C" Severity _1_STEPattribute_STEPread_(::STEPattribute* self, istream & in, InstMgrBase * instances, int addFileId, const char * currSch, bool strict) { return self->STEPread(in, instances, addFileId, currSch, strict); }
extern "C" string _1_STEPattribute_asStr_(const ::STEPattribute *self, const char * currSch) { return self->asStr(currSch); }
extern "C" const char * _2_STEPattribute_asStr_(const ::STEPattribute *self, std::string & __arg0, const char * __arg1) { return self->asStr(__arg0, __arg1); }
extern "C" void _1_STEPattribute_STEPwrite_(::STEPattribute* self, ostream & out, const char * currSch) { self->STEPwrite(out, currSch); }
extern "C" void _1_STEPattribute_ShallowCopy_(::STEPattribute* self, const STEPattribute * sa) { self->ShallowCopy(sa); }
extern "C" Severity _1_STEPattribute_set_null_(::STEPattribute* self) { return self->set_null(); }
extern "C" SDAI_Integer * _1_STEPattribute_Integer_(::STEPattribute* self) { return self->Integer(); }
extern "C" SDAI_Real * _1_STEPattribute_Real_(::STEPattribute* self) { return self->Real(); }
extern "C" SDAI_Real * _1_STEPattribute_Number_(::STEPattribute* self) { return self->Number(); }
extern "C" SDAI_String * _1_STEPattribute_String_(::STEPattribute* self) { return self->String(); }
extern "C" SDAI_Binary * _1_STEPattribute_Binary_(::STEPattribute* self) { return self->Binary(); }
extern "C" SDAI_Application_instance * _1_STEPattribute_Entity_(::STEPattribute* self) { return self->Entity(); }
extern "C" STEPaggregate * _1_STEPattribute_Aggregate_(::STEPattribute* self) { return self->Aggregate(); }
extern "C" SDAI_Enum * _1_STEPattribute_Enum_(::STEPattribute* self) { return self->Enum(); }
extern "C" SDAI_LOGICAL * _1_STEPattribute_Logical_(::STEPattribute* self) { return self->Logical(); }
extern "C" SDAI_BOOLEAN * _1_STEPattribute_Boolean_(::STEPattribute* self) { return self->Boolean(); }
extern "C" SDAI_Select * _1_STEPattribute_Select_(::STEPattribute* self) { return self->Select(); }
extern "C" SCLundefined * _1_STEPattribute_Undefined_(::STEPattribute* self) { return self->Undefined(); }
extern "C" void _2_STEPattribute_Integer_(::STEPattribute* self, SDAI_Integer * n) { self->Integer(n); }
extern "C" void _2_STEPattribute_Real_(::STEPattribute* self, SDAI_Real * n) { self->Real(n); }
extern "C" void _2_STEPattribute_Number_(::STEPattribute* self, SDAI_Real * n) { self->Number(n); }
extern "C" void _2_STEPattribute_String_(::STEPattribute* self, SDAI_String * str) { self->String(str); }
extern "C" void _2_STEPattribute_Binary_(::STEPattribute* self, SDAI_Binary * bin) { self->Binary(bin); }
extern "C" void _2_STEPattribute_Entity_(::STEPattribute* self, SDAI_Application_instance * ent) { self->Entity(ent); }
extern "C" void _2_STEPattribute_Aggregate_(::STEPattribute* self, STEPaggregate * aggr) { self->Aggregate(aggr); }
extern "C" void _2_STEPattribute_Enum_(::STEPattribute* self, SDAI_Enum * enu) { self->Enum(enu); }
extern "C" void _2_STEPattribute_Logical_(::STEPattribute* self, SDAI_LOGICAL * log) { self->Logical(log); }
extern "C" void _2_STEPattribute_Boolean_(::STEPattribute* self, SDAI_BOOLEAN * boo) { self->Boolean(boo); }
extern "C" void _2_STEPattribute_Select_(::STEPattribute* self, SDAI_Select * sel) { self->Select(sel); }
extern "C" void _2_STEPattribute_Undefined_(::STEPattribute* self, SCLundefined * undef) { self->Undefined(undef); }
extern "C" bool _1_STEPattribute_Nullable_(const ::STEPattribute *self) { return self->Nullable(); }
extern "C" bool _1_STEPattribute_is_null_(const ::STEPattribute *self) { return self->is_null(); }
extern "C" const char * _1_STEPattribute_Name_(const ::STEPattribute *self) { return self->Name(); }
extern "C" std::string _1_STEPattribute_TypeName_(const ::STEPattribute *self) { return self->TypeName(); }
extern "C" BASE_TYPE _1_STEPattribute_Type_(const ::STEPattribute *self) { return self->Type(); }
extern "C" BASE_TYPE _1_STEPattribute_NonRefType_(const ::STEPattribute *self) { return self->NonRefType(); }
extern "C" BASE_TYPE _1_STEPattribute_BaseType_(const ::STEPattribute *self) { return self->BaseType(); }
extern "C" const TypeDescriptor * _1_STEPattribute_ReferentType_(const ::STEPattribute *self) { return self->ReferentType(); }
extern "C" Severity _1_STEPattribute_ValidLevel_(::STEPattribute* self, const char * attrValue, ErrorDescriptor * error, InstMgrBase * im, bool clearError) { return self->ValidLevel(attrValue, error, im, clearError); }
extern "C" ::STEPattribute _1_STEPattribute_init_(const STEPattribute & a) { return ::STEPattribute(a); }
extern "C" ::STEPattribute _2_STEPattribute_init_() { return ::STEPattribute(); }
extern "C" void _1_STEPattribute_deinit_(::STEPattribute *self) { self->~STEPattribute(); }
extern "C" ::STEPattribute _3_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Integer * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _4_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Binary * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _5_STEPattribute_init_(const class AttrDescriptor & d, SDAI_String * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _6_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Real * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _7_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Application_instance ** p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _8_STEPattribute_init_(const class AttrDescriptor & d, STEPaggregate * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _9_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Enum * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _10_STEPattribute_init_(const class AttrDescriptor & d, SDAI_Select * p) { return ::STEPattribute(d, p); }
extern "C" ::STEPattribute _11_STEPattribute_init_(const class AttrDescriptor & d, SCLundefined * p) { return ::STEPattribute(d, p); }
extern "C" bool _1_STEPattribute_eql_(const STEPattribute & a1, const STEPattribute & a2) { return a1 == a2; }
extern "C" bool _1_STEPattribute_notEql_(const STEPattribute & a1, const STEPattribute & a2) { return a1 != a2; }
extern "C" bool _1_STEPattribute_sameADesc_(const STEPattribute & a1, const STEPattribute & a2) { return ::STEPattribute::sameADesc(a1, a2); }
